Remove AWS headers from tensorflow, and use headers from third_party …
tensorflow/io pull request #1241
Opened 2020-12-21 17:31 UTC by yongtang

…in tensorflow-io instead

This PR removes AWS headers from tensorflow and use headers
from third_party packages in tensorflow-io instead

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2020-12-21 17:40 UTC, kvignesh1420 approved these changes
LGTM. @yongtang lint check is failing though!

2020-12-21 17:47 UTC, terrytangyuan approved these changes

2020-12-21 17:47 UTC, vnvo2409 commented
@yongtang Do you think that we should remove `curl`, `boringssl` as well because in #1240, we are missing `curl_easy_cleanup`

2020-12-21 18:21 UTC, yongtang commented
@kvignesh1420 @terrytangyuan  @vnvo2409 The PR has been updated with lint fixed and curl, boringssl headers removed as well.

2020-12-21 22:10 UTC, vnvo2409 commented
@yongtang. LGTM. Thank you!

2020-12-22 02:39 UTC, vnvo2409 commented
@yongtang I think there is one more leak with `absl::StrCat`. I haven't tried this patch yet, but when I loaded `libtensorflow_io_plugins.so` , it said that there was a mismatch with the symbol of `absl::StrCat`. I think we have to exclude some more headers :confused:

2020-12-22 06:44 UTC, vnvo2409 commented
@yongtang 

Here is my list of excluded headers:
```
("/external/aws" not in e) and
("external/boringssl" not in e) and
("external/curl" not in e) and
("absl" not in e)
```

One thing I notice is `hadoop` do use `absl` but does not include `absl` in `deps`https://github.com/tensorflow/io/blob/e2bb58f0882a214343d49264be1bd33ead041f37/tensorflow_io/core/plugins/hdfs/BUILD#L17-L20

I think `hadoop` use `absl` of `tensorflow` which cause an ABI incompatibility. Let me take a look at `tf_configure.bzl`, I will try to extract only `tensorflow/c/` headers and put it into a separate rule ( `@local_config_tf//:tf_c_header_lib` ). 

Afterward, we could replace this https://github.com/tensorflow/io/blob/e2bb58f0882a214343d49264be1bd33ead041f37/tensorflow_io/core/plugins/BUILD#L17-L20 with `@local_config_tf//:tf_c_header_lib`.

2021-02-02 15:22 UTC, kvignesh1420 commented
@yongtang how can we proceed with this PR?

2021-02-02 23:20 UTC, yongtang commented
@kvignesh1420 The PR has been updated. Now all external headers (not just aws/etc) have been excluded except for protobuf/grpc, which seems to be too embedded with tensorflow's headers.

Please take a look at the changes.

2021-02-08 12:14 UTC, kvignesh1420 commented on third_party/toolchains/tf/tf_configure.bzl
> +        files = "\n".join(sorted([e for e in _read_dir(repository_ctx, src_dir).splitlines() if ("/external/" not in e) and ("/absl" not in e)]))
can we change it from `/absl` to `/absl/` just to be safe and consistent with the other condition?

2021-02-08 12:20 UTC, kvignesh1420 requested changes
@yongtang sorry for the delay. I was travelling and couldn't review it earlier. Can you please check the minor change request?

2021-02-08 15:46 UTC, yongtang commented
@kvignesh1420 The PR has been updated. Please take a look.

2021-02-08 16:15 UTC, kvignesh1420 approved these changes
thanks @yongtang

2021-02-08 16:15 UTC, merged