Update Kafka tutorial to work with Apache Kafka
tensorflow/io pull request #1266
Opened 2021-01-10 22:03 UTC by dalelane

Minor update to the Kafka tutorial to remove the dependency on
Confluent's distribution of Kafka, and instead work with vanilla
Apache Kafka.

Signed-off-by: Dale Lane <dale.lane@uk.ibm.com>

2021-01-10 22:04 UTC, dalelane commented
@googlebot I signed it!

2021-01-10 22:05 UTC, dalelane commented
context for this change: https://github.com/tensorflow/io/issues/802#issuecomment-755230465

2021-01-10 22:06 UTC, dalelane commented
@kvignesh1420 As discussed - a small update to the Kafka tutorial that gets it to run using vanilla Apache Kafka

2021-01-11 18:31 UTC, kvignesh1420 commented on docs/tutorials/kafka.ipynb
> +        "!pip install pandas"
@dalelane `sklearn` and `pandas` are pre-installed in colab. You can remove these lines.

2021-01-11 18:32 UTC, kvignesh1420 requested changes
Please check comments.

2021-01-11 18:47 UTC, dalelane commented
updated - thanks for the review!

2021-01-11 18:54 UTC, kvignesh1420 approved these changes
LGTM. I tried running the updated notebook and it ran without any errors.

2021-01-12 13:22 UTC, merged