Experimental: Add initial wavefront/obj parser for vertices
tensorflow/io pull request #1315
Opened 2021-02-26 01:33 UTC by yongtang

This PR is an early experimental implementation of wavefront obj
parser in tensorflow-io for 3D objects.
This PR is the first step to obtain raw vertices in float32
tensor with shape of `[n, 3]`.

Additional follow up PRs will be needed to handle meshs with
different shapes (not sure if ragged tensor will be a good fit
in that case)

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2021-02-26 05:18 UTC, burgerkingeater commented
do you have any introduction to wavefront format? Can you link it in the PR given it's a less known format.

2021-02-26 17:22 UTC, yongtang commented
@burgerkingeater obj file is a simple ASCII format for 3D models (http://paulbourke.net/dataformats/obj/). I have updated the PR with additional description. Please take a look.

2021-03-04 14:56 UTC, kvignesh1420 commented on tensorflow_io/core/python/experimental/image_ops.py
> +      contents: A `Tensor` of type `string`. 0-D. The Wavefront (obj) file.
@yongtang I think
`contents: A Tensor of type string. 0-D.  Wavefront (obj) file.` 

be replaced with
`contents: A 0 dimensional Tensor of type string, i.e the content of the Wavefront (.obj) file.`

2021-03-04 15:00 UTC, kvignesh1420 requested changes
@yongtang thanks for adding the support for the wavefront `.obj` file format. Please check the minor docstring change.

2021-03-05 16:48 UTC, yongtang commented
@kvignesh1420 Thanks for the review. The PR has been updated. Please take a look.

2021-03-05 17:06 UTC, kvignesh1420 approved these changes
LGTM.

2021-03-05 17:08 UTC, merged