Enable python 3.9 build on macOS
tensorflow/io pull request #1324
Opened 2021-03-11 21:21 UTC by yongtang

This PR enables python 3.9 build on macOS, as tf-nightly
is available with macOS now.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2021-03-11 21:21 UTC, terrytangyuan approved these changes

2021-03-12 10:54 UTC, kvignesh1420 requested changes
@yongtang can you please rebase and trigger the CI jobs once. Thanks.

2021-03-13 03:35 UTC, yongtang commented
Thanks @kvignesh1420. The PR has been updated.

2021-03-13 06:23 UTC, kvignesh1420 approved these changes

2021-03-13 06:24 UTC, merged